# Generated by Django 5.1 on 2024-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性別')),
                ('password', models.CharField(max_length=16, verbose_name='密碼')),
                ('age', models.IntegerField(verbose_name='年齡')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='賬戶餘額')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注冊日期')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='簡介')),
            ],
        ),
    ]
