# Generated by Django 5.1 on 2024-08-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
    ]
